server:
  port: 8080

spring:
  jpa:
    generate-ddl: false
    # 输出sql语句
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:demo;
    username: sa
    password:
    type: com.alibaba.druid.pool.DruidDataSource    # 使用阿里druid连接池
    druid:
      min-idle: 2
      initial-size: 5
      max-active: 10
      max-wait: 5000
      validation-query: select '1' from dual

  h2:
    console:
      enabled: true
      # 映射h2
      path: /h2

  flyway:
    clean-on-validation-error: true # 仅限开发环境使用
    locations: classpath:/db/migration

juhe:
  appKey: 28f53371cd64d295d5d038bc80ba05b6
  url: http://web.juhe.cn:8080/finance/stock/hs